name: Debug Workspace

on:
  workflow_dispatch:
    inputs:
      version:
        description: some input
        default: ''
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: list directory including hidden files
        run: ls -la

      - name: print certain yaml file
        run: cat .github/workflows/debug-workspace.yml

      - name: Update certain yaml file
        uses: fjogeleit/yaml-update-action@v0.3.0
        with:
          valueFile: '.github/workflows/debug-workspace.yml'
          propertyPath: 'on.workflow_dispatch.inputs.version.default'
          commitChange: 'false'
          updateFile: 'true'
          value: works

      - name: print certain yaml file again and expect field to be updated
        run: cat .github/workflows/debug-workspace.yml
