name: Release

on: 
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: 'Get Previous tag'
        id: latest_tag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Identify current version
        id: current_version
        uses: christian-draeger/read-properties@1.0.0
        with:
          path: './gradle.properties'
          property: 'VERSION_NAME'
      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.0
        with:
          current-version: ${{ steps.current_version.outputs.value }}
          version-fragment: ${{ steps.latest_tag.outputs.tag }}
      - name: Identify current version
        id: current_version
        uses: christian-draeger/write-properties@1.0.0
        with:
          path: './gradle.properties'
          property: 'VERSION_NAME'
          value: ${{ steps.bump_version.outputs.next-version }}
      - name: verify version bump
        id: current_version
        uses: christian-draeger/read-properties@1.0.0
        with:
          path: './gradle.properties'
          property: 'VERSION_NAME'
#      - uses: mikeal/publish-to-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
